### ISSUE TITLE
Macro-generated code causes plugin to crash during coverageReport task

### ISSUE THREAD

**Issue by ryan-williams** [scoverage/sbt-coveralls#102]
cf. [Travis build](https://travis-ci.org/hammerlab/iterators/jobs/297768551)

```
[info] Generating scoverage reports...
[info] Written Cobertura report [/home/travis/build/hammerlab/iterators/core/target/scala-2.11/coverage-report/cobertura.xml]
java.lang.RuntimeException: No source root found for '/home/travis/build/hammerlab/iterators/<macro>' (source roots: '/home/travis/build/hammerlab/iterators/core/src/main/scala/')
	at scoverage.report.BaseReportWriter.relativeSource(BaseReportWriter.scala:28)
	at scoverage.report.BaseReportWriter.relativeSource(BaseReportWriter.scala:16)
	at scoverage.report.CoberturaXmlWriter.klass(CoberturaXmlWriter.scala:42)
	at scoverage.report.CoberturaXmlWriter$$anonfun$pack$1.apply(CoberturaXmlWriter.scala:66)
	at scoverage.report.CoberturaXmlWriter$$anonfun$pack$1.apply(CoberturaXmlWriter.scala:66)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
…
```

This repository has a simple scalameta macro-annotation that shuffles some code between a class and its companion object, and injects some implicit conversions.

**Comment by gslowikowski** [comment]
I don't understand, how your `@IteratorOps` annotation works, but shouldn't the generated methods be synthetic? Scoverage checks synthetic flag when instrumenting code.

**Comment by gslowikowski** [comment]
@ryan-williams I probably have a fix. I would like you to assist in verifying it, if you have time.

Please start with creating an issue in [scalac-scoverage-plugin](https://github.com/scoverage/scalac-scoverage-plugin/issues) issues. That is the right place.

**Comment by ryan-williams** [comment]
Thanks @gslowikowski, I was just meaning to put together a proper repro for this; filed https://github.com/scoverage/scalac-scoverage-plugin/issues/210.

Let me know if I can help!

**Comment by gslowikowski** [comment]
Closing the issue, this is not a problem with this plugin, but with `scalac-scoverage-plugin`.
