### ISSUE TITLE
Sbt coberalls fails with connection timeout

### ISSUE THREAD

**Issue by fhuertas** [scoverage/sbt-coveralls#108]
When I do coverage report to coveralls, 

Command: 

`sbt coveralls`

Result: 

```
[info] Loading settings from build.sbt,plugins.sbt ...
[info] Loading project definition from ***************
[info] Loading settings from build.sbt ...
[info] Set current project to datafaker (in build file:/*************)
[info] Repository = ./.git
[error] java.net.ConnectException: Connection timed out (Connection timed out)
[error]         at java.net.PlainSocketImpl.socketConnect(Native Method)
[error]         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[error]         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[error]         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[error]         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[error]         at java.net.Socket.connect(Socket.java:589)
[error]         at java.net.Socket.connect(Socket.java:538)
[error]         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[error]         at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[error]         at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[error]         at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[error]         at sun.net.www.http.HttpClient.New(HttpClient.java:339)
[error]         at sun.net.www.http.HttpClient.New(HttpClient.java:357)
[error]         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
[error]         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[error]         at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1040)
[error]         at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1038)
[error]         at java.security.AccessController.doPrivileged(Native Method)
[error]         at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[error]         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1037)
[error]         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
[error]         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[error]         at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[error]         at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
[error]         at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
[error]         at java.security.AccessController.doPrivileged(Native Method)
[error]         at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[error]         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1304)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1270)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:264)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1161)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1045)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:959)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
[error]         at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
[error]         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
[error]         at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
[error]         at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
[error]         at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
[error]         at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[error]         at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
[error]         at scala.xml.factory.XMLLoader.loadXML(XMLLoader.scala:41)
[error]         at scala.xml.factory.XMLLoader.loadXML$(XMLLoader.scala:37)
[error]         at scala.xml.XML$.loadXML(XML.scala:60)
[error]         at scala.xml.factory.XMLLoader.loadFile(XMLLoader.scala:48)
[error]         at scala.xml.factory.XMLLoader.loadFile$(XMLLoader.scala:48)
[error]         at scala.xml.XML$.loadFile(XML.scala:60)
[error]         at org.scoverage.coveralls.CoberturaMultiSourceReader.<init>(CoberturaMultiSourceReader.scala:35)
[error]         at org.scoverage.coveralls.CoverallsPlugin$.$anonfun$coverallsTask$1(CoverallsPlugin.scala:104)
[error]         at org.scoverage.coveralls.CoverallsPlugin$.$anonfun$coverallsTask$1$adapted(CoverallsPlugin.scala:54)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (coveralls) java.net.ConnectException: Connection timed out (Connection timed out)

```

**Comment by fhuertas** [comment]
Now work, maybe the problem was a specific problem of this weekend
