### ISSUE TITLE
JsonParseException when uploading reports to coveralls

### ISSUE THREAD

**Issue by nrinaudo** [scoverage/sbt-coveralls#16]
I've just upgraded to version 0.99.2.1 of `org.scoverage.sbt-scoverage`, which seems to work absolutely fine on its own - even though my use case may be a bit on the complex side, cross-compiling sub-projects to 2.10.4 and 2.11.

I'm trying to get it to integrate with coveralls, and while the setup instructions are clear and easy to follow, I'm getting nasty stack traces (appended at the end of this ticket).

It might be something I've done wrong, in which case I apologise for wasting your time, but I feel that the configuration instructions are clear enough and easy enough to follow that I'm inclined to think there might be issues with running `sbt-coveralls` against the brand-new (as of this  morning) `sbt-coverage`.

I don't know whether that's any help, but the issues I'm having are with the following projet: 
[Fetch](https://github.com/nrinaudo/fetch).
```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@5925bfa; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1369)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:532)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:453)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleUnexpectedValue(ReaderBasedJsonParser.java:1386)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:669)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:2926)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2873)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
	at com.github.theon.coveralls.CoverallsClient.postFile(CoverallsClient.scala:37)
	at AbstractCoverallsPlugin$class.coverallsCommand(CoverallsPlugin.scala:155)
	at CoverallsPlugin$.coverallsCommand(CoverallsPlugin.scala:12)
	at CoverallsPlugin$$anonfun$coverallsSettings$7.apply(CoverallsPlugin.scala:67)
	at CoverallsPlugin$$anonfun$coverallsSettings$7.apply(CoverallsPlugin.scala:67)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
[error] (json4s-jackson/*:coveralls) com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
[error]  at [Source: java.io.StringReader@5925bfa; line: 1, column: 2]
```

**Comment by fommil** [comment]
@rorygraves vote to close as old version

**Comment by rorygraves** [comment]
Closing as fixed on master.
