### ISSUE TITLE
Create a release of sbt-coveralls with jackson 2.13.1

### ISSUE THREAD

**Issue by mdedetrich** [scoverage/sbt-coveralls#179]
I am currently adding sbt-dependency-check to an existing project that is using sbt-coveralls and its failing to build because sbt-coveralls is using an older version of jackson, i.e.

```
[error] com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.12.3 requires Jackson Databind version >= 2.12.0 and < 2.13.0
[error] 	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule(JacksonModule.scala:61)
[error] 	at com.fasterxml.jackson.module.scala.JacksonModule.setupModule$(JacksonModule.scala:46)
[error] 	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:17)
[error] 	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:853)
[error] 	at org.scoverage.coveralls.CoverallsClient.newMapper(CoverallsClient.scala:21)
[error] 	at org.scoverage.coveralls.CoverallsClient.<init>(CoverallsClient.scala:16)
[error] 	at org.scoverage.coveralls.CoverallsPlugin$.$anonfun$coverallsTask$2(CoverallsPlugin.scala:80)
[error] 	at org.scoverage.coveralls.CoverallsPlugin$.$anonfun$coverallsTask$2$adapted(CoverallsPlugin.scala:58)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2[219](https://github.com/aiven/guardian-for-apache-kafka/runs/5429575010?check_suite_focus=true#step:8:219)$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
```

(see https://github.com/aiven/guardian-for-apache-kafka/pull/130#issuecomment-1059619307 for more details)

I noticed recently that the jackson scala module was updated to 2.13.1 at https://github.com/scoverage/sbt-coveralls/commit/492da30887cb20834d0d754c3251864ed8c17728 which should fix this issue, would it be possible to create a release with this new version?

**Comment by ckipp01** [comment]
Hey @mdedetrich 1.3.2 is currently being released now. Give it a bit of time to sync, and then report back if you have any issues.

**Comment by mdedetrich** [comment]
Many thanks, I can confirm that it worked!
