### ISSUE TITLE
NoSuchMethod during upload

### ISSUE THREAD

**Issue by sellout** [scoverage/sbt-coveralls#22]
After all the coverage data is collected, I get `java.lang.NoSuchMethodError: scalaj.http.MultiPart.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[B)V`. Now, as far as I can tell, that method _does_ exist, and I have no idea why this is happening.

Here is our config:
```scala
resolvers += Classpaths.sbtPluginReleases

addSbtPlugin("org.scoverage" %% "sbt-scoverage" % "0.99.7.1")

addSbtPlugin("org.scoverage" %% "sbt-coveralls" % "0.99.0")
```

and the package resolution, from scoverage through scalaj-http.
```
[info] Resolving org.scoverage#sbt-scoverage;0.99.7.1 ...
[info] Resolving org.scoverage#scalac-scoverage-plugin_2.10;0.99.7 ...
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
[info] Resolving commons-io#commons-io;2.4 ...
[info] Resolving org.scoverage#sbt-coveralls;0.99.0 ...
[info] Resolving com.fasterxml.jackson.core#jackson-core;2.4.2 ...
[info] Resolving com.fasterxml.jackson.module#jackson-module-scala_2.10;2.4.2 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.4 ...
[info] Resolving com.fasterxml.jackson.core#jackson-annotations;2.4.2 ...
[info] Resolving com.fasterxml.jackson.core#jackson-databind;2.4.2 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving com.google.code.findbugs#jsr305;2.0.1 ...
[info] Resolving com.google.guava#guava;15.0 ...
[info] Resolving org.eclipse.jgit#org.eclipse.jgit;3.4.1.201406201815-r ...
[info] Resolving com.jcraft#jsch;0.1.50 ...
[info] Resolving com.googlecode.javaewah#JavaEWAH;0.7.9 ...
[info] Resolving org.apache.httpcomponents#httpclient;4.1.3 ...
[info] Resolving org.apache.httpcomponents#httpcore;4.1.4 ...
[info] Resolving commons-logging#commons-logging;1.1.1 ...
[info] Resolving commons-codec#commons-codec;1.4 ...
[info] Resolving org.scalaj#scalaj-http_2.10;0.3.16 ...
```

Finally, the full stack trace:
```
java.lang.NoSuchMethodError: scalaj.http.MultiPart.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[B)V
	at com.github.theon.coveralls.ScalaJHttpClient.multipart(CoverallsClient.scala:52)
	at com.github.theon.coveralls.CoverallsClient.postFile(CoverallsClient.scala:36)
	at AbstractCoverallsPlugin$class.coverallsCommand(CoverallsPlugin.scala:156)
	at CoverallsPlugin$.coverallsCommand(CoverallsPlugin.scala:12)
	at CoverallsPlugin$$anonfun$coverallsSettings$7.apply(CoverallsPlugin.scala:67)
	at CoverallsPlugin$$anonfun$coverallsSettings$7.apply(CoverallsPlugin.scala:67)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:35)
	at scala.Function10$$anonfun$tupled$1.apply(Function10.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fommil** [comment]
@rorygraves vote to close as old version

**Comment by rorygraves** [comment]
@sellout @MeiSign  Please retry on a newer version - please reopen if you can still duplicate.

**Comment by riomus** [comment]
I'm getting same error

`java.lang.NoSuchMethodError: scalaj.http.Http$.multipart(Ljava/lang/String;Lscala/collection/Seq;)Lscalaj/http/Http$Request;
	at org.scoverage.coveralls.ScalaJHttpClient.multipart(CoverallsClient.scala:65)
	at org.scoverage.coveralls.CoverallsClient.postFile(CoverallsClient.scala:32)
	at org.scoverage.coveralls.CoverallsPlugin$.doCoveralls(CoverallsPlugin.scala:110)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$coverallsCommand$1.apply(CoverallsPlugin.scala:34)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$coverallsCommand$1.apply(CoverallsPlugin.scala:34)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: scalaj.http.Http$.multipart(Ljava/lang/String;Lscala/collection/Seq;)Lscalaj/http/Http$Request;`

on scala 2.10 and 2.11. sbt-coveralls version 1.0.3 (https://travis-ci.org/sparkling-graph/sparkling-graph/jobs/110665703)

**Comment by zouzias** [comment]
I get the same error as @riomus 

Any ideas: https://travis-ci.org/zouzias/spark-lucenerdd/jobs/151753453#L1479

**Comment by riomus** [comment]
Because no one was interested in that issue, I've switched to different code coverage analysis platform. I do not want to advertise anything so just check what my library (http://sparkling-graph.github.io) is using if you want to temporarily solve your issue.
