### ISSUE TITLE
sbt-coveralls 1.3.3 failing with `Could not find the cobertura.xml file. Did you call coverageAggregate?`

### ISSUE THREAD

**Issue by mdedetrich** [scoverage/sbt-coveralls#224]
With a simple bump to the sbt-coveralls version my project started failing with the following exception, i.e.

```
[error] java.lang.RuntimeException: Could not find the cobertura.xml file. Did you call coverageAggregate?
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at org.scoverage.coveralls.CoverallsPlugin$.$anonfun$coverallsTask$2(CoverallsPlugin.scala:72)
[error] 	at org.scoverage.coveralls.CoverallsPlugin$.$anonfun$coverallsTask$2$adapted(CoverallsPlugin.scala:67)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:829)
[error] (coveralls) Could not find the cobertura.xml file. Did you call coverageAggregate?
```

See PR at https://github.com/aiven/guardian-for-apache-kafka/pull/346 for more details

**Comment by jacemale-ovo** [comment]
I think this might be related to my issue #222

**Comment by ruippeixotog** [comment]
Same here - PureConfig can't update to 1.3.3 because of the same error (https://github.com/pureconfig/pureconfig/pull/1429). We're calling `coverageAggregate` and this is working well in v1.3.2.

I tried to go through the PRs to see what changed, but I stumbled into https://github.com/scoverage/sbt-coveralls/pull/214. I imagine this big merge might have introduced a regression, @rolandtritsch.

**Comment by rolandtritsch** [comment]
Hi Matthew. This should be fixed now. Thanks for reporting the issue. Please close the issue after you have confirmed that it works. - https://github.com/scoverage/sbt-coveralls/releases/tag/v1.3.5

**Comment by mdedetrich** [comment]
Indeed it works now https://github.com/aiven/guardian-for-apache-kafka/pull/347, closing the issue. Thanks for solving it!
