### ISSUE TITLE
FileNotFoundException for multi-module projects

### ISSUE THREAD

**Issue by MichaelJAllen** [scoverage/sbt-coveralls#51]
FIrstly, thanks for providing such useful test coverage tools for Scala projects! I really appreciate your efforts!

I've just added your `sbt-scoverage` and `sbt-coveralls` plugins to my _[Facsimile](https://github.com/Facsimile/facsimile)_ project. This is a multi-module project in which the sources are stored in separate sub-directories off the project root. (There are two such sub-modules, *macros* and *core*, both of which are in sub-directories of the same name.)

The `coverage` and `coverageAggregate` `sbt` tasks both complete OK, reporting a coverage of  100% for the first module and around 67% for the second. However, when the `coveralls` command is executed, it fails with a `FileNotFoundException`. It appears to be looking for a source file that is located almost directly off the root, rather than in the corresponding module's `src/main/scala` sub-directory. This is, it's looking for a file called:

`/home/travis/build/Facsimile/facsimile/org/facsim/measure/Specific.scala`

when it should be looking for a file called:

`/home/travis/build/Facsimile/facsimile/core/src/main/scala/org/facsim/measure/Specific.scala`

Any ideas? Is this a consequence of aggregating the coverage reports?

Here's the Travis CI build log, which includes the coverage output from each set of tests and the `coverageAggregate` command commences.

```
...
< macro module test output removed >
...
[info] Reading scoverage instrumentation [/home/travis/build/Facsimile/facsimile/macro/target/scala-2.11/scoverage-data/scoverage.coverage.xml]
[info] Reading scoverage measurements...
[info] Generating scoverage reports...
[info] Written Cobertura report [/home/travis/build/Facsimile/facsimile/macro/target/scala-2.11/coverage-report/cobertura.xml]
[info] Written XML coverage report [/home/travis/build/Facsimile/facsimile/macro/target/scala-2.11/scoverage-report/scoverage.xml]
[info] Written HTML coverage report [/home/travis/build/Facsimile/facsimile/macro/target/scala-2.11/scoverage-report/index.html]
[info] Coverage reports completed
[info] All done. Coverage was [100.00%]
[info] Run completed in 3 seconds, 113 milliseconds.
[info] Total number of tests run: 30
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 30, failed 0, canceled 0, ignored 11, pending 0
[info] All tests passed.
...
< core module test output removed >
...
[info] Reading scoverage instrumentation [/home/travis/build/Facsimile/facsimile/core/target/scala-2.11/scoverage-data/scoverage.coverage.xml]
[info] Reading scoverage measurements...
[info] Generating scoverage reports...
[info] Written Cobertura report [/home/travis/build/Facsimile/facsimile/core/target/scala-2.11/coverage-report/cobertura.xml]
[info] Written XML coverage report [/home/travis/build/Facsimile/facsimile/core/target/scala-2.11/scoverage-report/scoverage.xml]
[info] Written HTML coverage report [/home/travis/build/Facsimile/facsimile/core/target/scala-2.11/scoverage-report/index.html]
[info] Coverage reports completed
[info] All done. Coverage was [67.10%]
[info] Run completed in 6 seconds, 386 milliseconds.
[info] Total number of tests run: 164
[info] Suites: completed 17, aborted 0
[info] Tests: succeeded 164, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 95 s, completed May 20, 2015 6:11:57 PM
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[info] Loading project definition from /home/travis/build/Facsimile/facsimile/project
[info] Set current project to Facsimile Simulation Library (in build file:/home/travis/build/Facsimile/facsimile/)
[info] Setting version to 2.11.6
[info] Reapplying settings...
[info] Set current project to Facsimile Simulation Library (in build file:/home/travis/build/Facsimile/facsimile/)
[info] Aggregating coverage from subprojects...
[info] Found 2 subproject report files [/home/travis/build/Facsimile/facsimile/core/target/scala-2.11/scoverage-report/scoverage.xml,/home/travis/build/Facsimile/facsimile/macro/target/scala-2.11/scoverage-report/scoverage.xml]
[info] Generating scoverage reports...
[info] Written Cobertura report [/home/travis/build/Facsimile/facsimile/target/scala-2.11/coverage-report/cobertura.xml]
[info] Written XML coverage report [/home/travis/build/Facsimile/facsimile/target/scala-2.11/scoverage-report/scoverage.xml]
[info] Written HTML coverage report [/home/travis/build/Facsimile/facsimile/target/scala-2.11/scoverage-report/index.html]
[info] Coverage reports completed
[info] Aggregation complete. Coverage was [67.39]
[success] Total time: 3 s, completed May 20, 2015 6:12:12 PM
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[info] Loading project definition from /home/travis/build/Facsimile/facsimile/project
[info] Set current project to Facsimile Simulation Library (in build file:/home/travis/build/Facsimile/facsimile/)
[info] Setting version to 2.11.6
[info] Reapplying settings...
[info] Set current project to Facsimile Simulation Library (in build file:/home/travis/build/Facsimile/facsimile/)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Repository = ./.git
java.io.FileNotFoundException: /home/travis/build/Facsimile/facsimile/org/facsim/measure/Specific.scala (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at scala.io.Source$.fromFile(Source.scala:90)
	at scala.io.Source$.fromFile(Source.scala:75)
	at scala.io.Source$.fromFile(Source.scala:53)
	at org.scoverage.coveralls.CoberturaReader.reportForSource(CoberturaReader.scala:34)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$doCoveralls$5.apply(CoverallsPlugin.scala:91)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$doCoveralls$5.apply(CoverallsPlugin.scala:90)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:153)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
	at org.scoverage.coveralls.CoverallsPlugin$.doCoveralls(CoverallsPlugin.scala:90)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$coverallsCommand$1.apply(CoverallsPlugin.scala:28)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$coverallsCommand$1.apply(CoverallsPlugin.scala:28)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.io.FileNotFoundException: /home/travis/build/Facsimile/facsimile/org/facsim/measure/Specific.scala (No such file or directory)
[error] Use 'last' for the full log.
The command "sbt ++$TRAVIS_SCALA_VERSION scalastyle coverage test && sbt ++$TRAVIS_SCALA_VERSION coverageAggregate && sbt ++$TRAVIS_SCALA_VERSION coveralls" exited with 1.
```

**Comment by MichaelJAllen** [comment]
Whoops! It looks like this is a duplicate of Issue #49, which I didn't initially see as it had been closed.
