### ISSUE TITLE
Broken cobertura schema?

### ISSUE THREAD

**Issue by lancegatlin** [scoverage/sbt-coveralls#56]
java.io.IOException: Server returned HTTP response code: 503 for URL: http://cobertura.sourceforge.net/xml/coverage-04.dtd

Wondering if cobertura has migrated from sourceforge?

**Comment by lancegatlin** [comment]
java.io.IOException: Server returned HTTP response code: 503 for URL: http://cobertura.sourceforge.net/xml/coverage-04.dtd
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:643)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1297)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1264)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:263)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1164)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1050)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:964)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:332)
	at scala.xml.factory.XMLLoader$class.loadXML(XMLLoader.scala:40)
	at scala.xml.XML$.loadXML(XML.scala:57)
	at scala.xml.factory.XMLLoader$class.loadFile(XMLLoader.scala:47)
	at scala.xml.XML$.loadFile(XML.scala:57)
	at org.scoverage.coveralls.CoberturaReader.<init>(CoberturaReader.scala:9)
	at org.scoverage.coveralls.CoverallsPlugin$.doCoveralls(CoverallsPlugin.scala:85)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$coverallsCommand$1.apply(CoverallsPlugin.scala:28)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$coverallsCommand$1.apply(CoverallsPlugin.scala:28)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:29)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)

**Comment by lancegatlin** [comment]
So it appears http://cobertura.sourceforge.net/ is down. Which isn't a code issue here, *however* if it should remain down can we possibly get a fix in to get around it?

**Comment by sksamuel** [comment]
Probably should just refer to it locally.

**Comment by lancegatlin** [comment]
Apologies - do you have any suggestions on how to fix this for travis? I can fix locally for myself.

**Comment by rorygraves** [comment]
A fix has been pushed into scalac-scoverage plugin (where the actual reference exists).  @sksamuel will have to kick out a build to make it all happy.

**Comment by sksamuel** [comment]
Is it all ready for a release?

**Comment by rorygraves** [comment]
I think so - it worked locally - n.b. it is not the coveralls plugin that needs fixing but the scalac-scoverage and thus the sbt-scoverage plugin that needs to  be updated.

**Comment by sksamuel** [comment]
Ok @pdalpra is doing some changes to the sbt client, once complete I'll do a release.

**Comment by sksamuel** [comment]
Just released 1.1.1 of the scalac plugin, will get an sbt release out asap.
