### ISSUE TITLE
Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by kshakir** [scoverage/sbt-coveralls#63]
After our build runs, the coveralls reports are not uploaded, and we see the stack trace below that mentions "Received fatal alert: handshake_failure".

Possibly a similar [cipher suite](https://github.com/scoverage/sbt-coveralls/blob/9dc6ed50b4da1de32ca037213e2c15326cd0ca0c/src/main/scala/org/scoverage/coveralls/CoverallsClient.scala#L81) issue to #13, as https://www.ssllabs.com/ssltest/analyze.html?d=coveralls.io says the current cert is valid from "Wed, 07 Oct 2015 00:00:00 UTC"?

Running on Travis with the following .travis.yml:

```
sudo: false
language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8

script: sbt clean coverage test
after_success: sbt coveralls
```

project/plugins.sbt:

```
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.0.4")

addSbtPlugin("org.scoverage" % "sbt-coveralls" % "1.0.0")
```

Seeing this stack trace:

```java
$ sbt coveralls
Detected sbt version 0.13.5
Using jvm options defined in file /etc/sbt/jvmopts
# Executing command line:
/usr/lib/jvm/java-8-oracle/bin/java
-Xms2048M
-Xmx2048M
-Xss6M
-XX:MaxPermSize=512M
-jar
/home/travis/.sbt/launchers/0.13.5/sbt-launch.jar
warn
"set javaHome in ThisBuild := Some(file("/usr/lib/jvm/java-8-oracle"))"
info
coveralls
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0
[info] Loading project definition from /home/travis/build/redacted/project
[info] Set current project to redacted (in build file:/home/travis/build/redacted/)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Repository = ./.git
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2011)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1113)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282)
	at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:90)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1249)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1247)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivileged(AccessController.java:713)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1246)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
	at scalaj.http.Http$$anonfun$3.apply(Http.scala:364)
	at scalaj.http.Http$$anonfun$3.apply(Http.scala:329)
	at scalaj.http.Http$Request.process(Http.scala:159)
	at org.scoverage.coveralls.ScalaJHttpClient.multipart(CoverallsClient.scala:71)
	at org.scoverage.coveralls.CoverallsClient.postFile(CoverallsClient.scala:33)
	at org.scoverage.coveralls.CoverallsPlugin$.doCoveralls(CoverallsPlugin.scala:97)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$coverallsCommand$1.apply(CoverallsPlugin.scala:28)
	at org.scoverage.coveralls.CoverallsPlugin$$anonfun$coverallsCommand$1.apply(CoverallsPlugin.scala:28)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:31)
	at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:31)
	at sbt.Command$.process(Command.scala:95)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:100)
	at sbt.State$$anon$1.process(State.scala:179)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:100)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.MainLoop$.next(MainLoop.scala:100)
	at sbt.MainLoop$.run(MainLoop.scala:93)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:71)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:66)
	at sbt.Using.apply(Using.scala:25)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:66)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:49)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:33)
	at sbt.MainLoop$.runLogged(MainLoop.scala:25)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:129)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:36)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:19)
	at xsbt.boot.Boot$.runImpl(Boot.scala:44)
	at xsbt.boot.Boot$.main(Boot.scala:20)
	at xsbt.boot.Boot.main(Boot.scala)
[error] javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
[error] Use 'last' for the full log.
```

**Comment by kshakir** [comment]
Closing this issue. sbt-coveralls 1.0.0 appears to be working again with the current cert on https://coveralls.io. The ssllabs site now says the cert is from "Sat, 10 Oct 2015 00:00:00 UTC". Something's changing, no idea what.
